---

##################################################
# this updates drac firmware
#
- name: update drac to latest firmware version
  hosts: drac
  gather_facts: false
  become: false

  roles:
    - role: drac
      when: drac is defined

- name: configure management host
  hosts: "{{ groups['controller'][0] }}"
  gather_facts: false
  become: true

  roles:
# this verifies ssh keys for initial connections
    - role: ssh_fingerprint_connect
# this configures the management host (the controller, usually) to manage vsphere
    - role: mgmt_config
# this creates and populates the nfs server on the management host
    - role: nfs

- name: configure esxi
  hosts: esxi
  gather_facts: false
  become: true
  vars:
    # this is domain user params
    user_name: user01
    user_password: P@ssW0rd!
    user_first_name: user01
    user_last_name: user01

  roles:
# this creates the custom esxi installation isos with custom kickstarts
    - role: iso
##################################################
# ONLY RUN THIS WHEN YOU WANT TO WIPE YOUR SERVERS
##################################################
    - role: esxi_provision
      when: wipe is defined
# this configures the provisioned esxi hosts
    - role: esxi_config

- name: deploy vcenter and configure cluster
  hosts: "{{ groups['controller'][0] }}"
  gather_facts: true
  become: true

  roles:
# this deploys and configures vcenter and creates the datacenter and cluster
    - role: esxi_vcenter

...
