---
# tasks file for nfs

- name: install nfs packages
  package:
    name: "nfs-utils"
    state: latest

- name: enable nfs export selinux boolean
  ansible.posix.seboolean:
    name: "nfs_export_all_ro"
    state: true
    persistent: true

- name: configure services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    masked: false
    state: started
  with_items:
    - "rpcbind"
    - "nfs-server"

- name: add nfs export directory
  ansible.builtin.file:
    path: "/export"
    state: directory
    mode: '0755'

- name: add nfs share configuration
  ansible.builtin.template:
    src: "exports.j2"
    dest: "/etc/exports"
    mode: '0644'
  notify:
  - reload nfs

- name: configure firewall for nfs
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - "mountd"
    - "nfs"
    - "rpc-bind"

...
