---
# tasks file for mgmt_config

- name: install epel key
  ansible.builtin.rpm_key:
    state: present
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

- name: install epel package
  ansible.builtin.yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: install python pyvmomi for vmware management
  ansible.builtin.package:
    name: python3-pyvmomi
    state: latest

...
